# Generated by Django 4.2.2 on 2023-06-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('positions', models.TextField(choices=[('fulltime', 'Fulltime'), ('remote', 'Remote')])),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
