# Generated by Django 4.2.2 on 2023-06-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_job_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='positions',
        ),
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20, null=True),
        ),
    ]
