# Generated by Django 4.2.2 on 2023-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
