# Generated by Django 4.2.2 on 2023-06-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_job_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.SlugField(null=True),
        ),
    ]
